# Generated by Django 3.1.7 on 2021-03-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullsAndCows', '0002_guess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='guess',
            field=models.CharField(default='guess', max_length=4),
        ),
    ]
