# Generated by Django 3.1.7 on 2021-03-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bullsAndCows', '0004_auto_20210329_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('summary', models.TextField(default='this is great')),
            ],
        ),
    ]
